# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titlt',
            new_name='title',
        ),
    ]
